import Gtk from 'gi://Gtk?version=4.0';
import Adw from 'gi://Adw?version=1';
import Gio from 'gi://Gio';
import GLib from 'gi://GLib';
import {create as note} from '../dist/desktop/widgets/sticky-note/widget.js';
import {create as weather} from '../dist/desktop/widgets/weather/widget.js';
import {create as playing} from '../dist/desktop/widgets/now-playing/widget.js';
import {forecastUrl, conditions} from '../dist/desktop/widgets/weather/model.js';
import {discoverWidgets, widgetInstances, WidgetHost} from '../dist/desktop/widgetHost.js';
import {widgetOptions} from '../dist/desktop/widgetSettings.js';
GLib.set_prgname('luna-desktop-desktop-api-test');
Adw.init();
Gtk.Settings.get_default().gtk_icon_theme_name = 'Papirus-Dark';
const loop = new GLib.MainLoop(null, false);
const wait = ms => new Promise(resolve => GLib.timeout_add(0, ms, () => { resolve(); return GLib.SOURCE_REMOVE; }));
function assert(value, message) { if (!value) throw Error(message); }
const root = Gio.File.new_for_uri(import.meta.url).get_parent().get_parent().get_child('dist').get_path();
const schema = Gio.SettingsSchemaSource.new_from_directory(`${root}/schemas`, Gio.SettingsSchemaSource.get_default(), false).lookup('org.gnome.shell.extensions.luna-desktop', true);
const settings = new Gio.Settings({settings_schema: schema});
const definitions = discoverWidgets(root);
const disposals = [];
function context(id, overrides = {}, state = {}) {
    const cleanups = [];
    disposals.push(() => { for (const cb of cleanups.reverse()) cb(); });
    return {id, options: {...widgetOptions(settings, definitions.find(d => d.id === id)), ...overrides},
        loadState: () => state, saveState: value => { state = value; }, onDispose: cb => cleanups.push(cb),
        every: (ms, cb) => { const source = GLib.timeout_add(0, ms, () => { cb(); return GLib.SOURCE_CONTINUE; }); cleanups.push(() => GLib.Source.remove(source)); }};
}
function descendants(widget) { const all = [widget]; for (let child = widget.get_first_child(); child; child = child.get_next_sibling()) all.push(...descendants(child)); return all; }
const window = new Gtk.Window({default_width: 1000, default_height: 700});
const cardCss = new Gtk.CssProvider();
cardCss.load_from_string('.desktop-widget { padding: 12px; border: 1px solid transparent; }');
Gtk.StyleContext.add_provider_for_display(imports.gi.Gdk.Display.get_default(), cardCss, Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION);
const fixed = new Gtk.Fixed(); window.set_child(fixed); window.present();
let failure, exported = [], host;
(async () => {
    assert(['weather','now-playing','sticky-note'].every(id => definitions.some(d => d.id === id)), 'New widgets discovered');
    const first = context('sticky-note'), second = context('sticky-note');
    const a = note(first), b = note(second);
    const noteActions = descendants(a).filter(item => item instanceof Gtk.Button && ['Note color, size, and appearance', 'Remove note'].includes(item.tooltip_text));
    assert(noteActions.length === 2 && noteActions.every(item => item.opacity === 0 && !item.can_target), 'Note actions start hidden without hover or keyboard focus');
    fixed.put(a, 20, 20); fixed.put(b, 330, 20); a.set_size_request(280,180); b.set_size_request(280,180);
    const editor = descendants(a).find(w => w instanceof Gtk.TextView);
    editor.buffer.text = 'First note\nSecond line <literal & text>';
    descendants(b).find(w => w instanceof Gtk.TextView).buffer.text = 'Independent note';
    await wait(450);
    assert(first.loadState().text.startsWith('First note\n'), 'Direct note typing saves multiline text');
    assert(second.loadState().text === 'Independent note', 'Notes have independent contents');
    assert(!editor.cursor_visible, 'Note does not show a caret before explicit editing');
    assert(!descendants(note(context('sticky-note', {interactive: false}))).find(w => w instanceof Gtk.TextView).editable, 'HUD-only note option');
    const weatherState = {key: JSON.stringify(['stockholm','SE','celsius']), updated: Date.now(), location: {name: 'Stockholm, SE', latitude: 59, longitude: 18},
        data: {current: {temperature_2m: 16.4, apparent_temperature: 14.1, weather_code: 0, is_day: 0, wind_speed_10m: 12},
            daily: {time: ['2026-09-26','2026-09-27','2026-09-28'],weather_code:[2,61,0],temperature_2m_max:[17,14,18],temperature_2m_min:[8,7,9]}}};
    const w = weather(context('weather', {city:'Stockholm', countryCode:'SE'}, weatherState)); fixed.put(w, 20, 250); w.set_size_request(300,220);
    assert(forecastUrl(weatherState.location, 'fahrenheit').includes('temperature_unit=fahrenheit'), 'Fahrenheit API parameter');
    assert(conditions(95)[0] === 'Thunderstorm', 'Weather code mapping');
    const minimalWeather = weather(context('weather', {city:'Stockholm', countryCode:'SE', showLocation:false, showConditions:false, showUpdated:false, showAttribution:false}, weatherState));
    assert(!minimalWeather.get_first_child().visible, 'Weather location can be hidden');
    assert(descendants(minimalWeather).filter(item => item instanceof Gtk.Label && ['Partly cloudy','Weather data by Open-Meteo'].includes(item.label)).every(item => !item.visible), 'Weather condition and credit can be hidden');
    const rootXml = '<node><interface name="org.mpris.MediaPlayer2"><property name="Identity" type="s" access="read"/><property name="DesktopEntry" type="s" access="read"/></interface></node>';
    const playerXml = '<node><interface name="org.mpris.MediaPlayer2.Player"><method name="PlayPause"/><method name="Next"/><method name="Previous"/><property name="PlaybackStatus" type="s" access="read"/><property name="Metadata" type="a{sv}" access="read"/>' + ['CanControl','CanPlay','CanPause','CanGoNext','CanGoPrevious'].map(n => `<property name="${n}" type="b" access="read"/>`).join('') + '</interface></node>';
    let calls = 0;
    const rootService = Gio.DBusExportedObject.wrapJSObject(rootXml, {Identity:'Test Player',DesktopEntry:'org.gnome.Music'});
    const playerService = Gio.DBusExportedObject.wrapJSObject(playerXml, {PlaybackStatus:'Playing', Metadata: {'xesam:title':new GLib.Variant('s','Test Track'), 'xesam:artist':new GLib.Variant('as',['Test Artist'])}, CanControl:true, CanPlay:true, CanPause:true, CanGoNext:true, CanGoPrevious:true, PlayPause(){ calls++; }, Next(){ calls++; }, Previous(){ calls++; }});
    exported = [rootService, playerService];
    for (const obj of exported) obj.export(Gio.DBus.session,'/org/mpris/MediaPlayer2');
    await new Promise((resolve,reject) => Gio.DBus.session.call('org.freedesktop.DBus','/org/freedesktop/DBus','org.freedesktop.DBus','RequestName',new GLib.Variant('(su)',['org.mpris.MediaPlayer2.LunaDesktopTest',0]),null,0,2000,null,(bus,result)=>{try{bus.call_finish(result);resolve();}catch(e){reject(e);}}));
    let mediaVisible = null;
    const mediaContext = context('now-playing', {controlsOnHover:false, hideWhenIdle:true, showVisualizer:true});
    mediaContext.setVisible = visible => { mediaVisible = visible; };
    const excludedContext = context('now-playing', {excludedApps: 'LunaDesktopTest', hideWhenIdle: true});
    let excludedVisible = null;
    excludedContext.setVisible = visible => { excludedVisible = visible; };
    const excluded = playing(excludedContext);
    const p = playing(mediaContext); fixed.put(p, 360,250); p.set_size_request(320,200);
    await wait(1200);
    assert(descendants(w).some(item => item instanceof Gtk.Label && item.label.includes('16°')), 'Cached weather renders current temperature');
    assert(descendants(w).some(item => item instanceof Gtk.Label && item.label.includes('Updated')), 'Fresh cache used without network');
    assert(descendants(p).some(item => item instanceof Gtk.Label && item.label === 'Test Track'), 'MPRIS metadata displayed');
    assert(mediaVisible === true, 'Active player makes widget visible');
    assert(excludedVisible === false && descendants(excluded).some(item => item instanceof Gtk.Label && item.label === 'Nothing playing'), 'Excluded player leaves widget idle');
    const play = descendants(p).find(item => item instanceof Gtk.Button && item.tooltip_text === 'Play or pause');
    assert(descendants(p).some(item => item instanceof Gtk.DrawingArea), 'Optional visualizer is created');
    assert(play.sensitive && play.icon_name === 'media-playback-pause-symbolic', 'MPRIS capabilities and playing state');
    play.emit('clicked'); await wait(150); assert(calls === 1, 'Playback command reaches player');
    for (const obj of exported) obj.unexport(); exported = [];
    await wait(2200);
    assert(descendants(p).some(item => item instanceof Gtk.Label && item.label === 'Nothing playing'), 'Player exit resets widget');
    assert(mediaVisible === false, 'Idle media hides entire widget');
    const instances = widgetInstances(definitions, ['sticky-note', 'sticky-note:test-2']);
    assert(instances.length === 2 && instances[1].typeId === 'sticky-note', 'Multiple instances resolve same module');
    const snap = new Gtk.Snapshot(); new Gtk.WidgetPaintable({widget:window}).snapshot(snap,window.get_width(),window.get_height());
    window.get_renderer().render_texture(snap.to_node(),null).save_to_png('/tmp/luna-desktop-new-widgets.png');
    settings.set_boolean('desktop-icons-enabled', false); settings.set_boolean('desktop-widgets-enabled', true);
    settings.set_strv('desktop-enabled-widgets', ['sticky-note','sticky-note:test-2']);
    host = new WidgetHost(root, settings);
    await host.mount([{fixed,window,monitor:{id:'test',primary:true,width:1000,height:700}}]);
    await wait(150);
    assert(host.instances[0].card.get_allocated_width() === host.instances[0].rect.width && host.instances[0].card.get_allocated_height() === host.instances[0].rect.height, 'Placement uses outer dimensions including padding and border');
    assert(host.instances.length === 2 && host.instances.every(i=>i.content instanceof Gtk.Overlay), 'Both notes mount with icons disabled');
    descendants(host.instances[0].content).find(w=>w instanceof Gtk.TextView).buffer.text = 'Saved instance one';
    descendants(host.instances[1].content).find(w=>w instanceof Gtk.TextView).buffer.text = 'Saved instance two';
    host.clear();
    await host.mount([{fixed,window,monitor:{id:'test',primary:true,width:1000,height:700}}]);
    assert(descendants(host.instances[0].content).find(w=>w instanceof Gtk.TextView).buffer.text === 'Saved instance one', 'Dispose flushes note text');
    assert(descendants(host.instances[1].content).find(w=>w instanceof Gtk.TextView).buffer.text === 'Saved instance two', 'Remount restores separate notes');
    const beforeSpacing = host.instances[0];
    settings.set_int('desktop-widget-edge-spacing', 0);
    await host.mount([{fixed,window,monitor:{id:'test',primary:true,width:1000,height:700}}]);
    assert(host.instances[0] !== beforeSpacing && host.instances[0].margin === 0, 'Changing edge spacing replaces stale drag and resize limits');
    assert(descendants(host.instances[0].content).find(w=>w instanceof Gtk.TextView).buffer.text === 'Saved instance one', 'Spacing change preserves note contents');
    const noteId = host.instances[0].id;
    const removeNote = descendants(host.instances[0].content).find(w => w instanceof Gtk.Button && w.tooltip_text === 'Remove note');
    removeNote.emit('clicked'); await wait(200);
    const windows = Gtk.Window.get_toplevels();
    let confirm;
    for (let i=0; i<windows.get_n_items(); i++) if(windows.get_item(i).title === 'Remove note?') confirm = windows.get_item(i);
    assert(confirm, 'Each note exposes removal outside Edit Desktop');
    confirm.response(Gtk.ResponseType.OK); await wait(100);
    assert(!settings.get_strv('desktop-enabled-widgets').includes(noteId) && settings.get_strv('desktop-enabled-widgets').length === 1, 'Removal affects only selected note');
    const cacheDir = `${GLib.get_user_data_dir()}/luna-desktop/widget-state`;
    GLib.mkdir_with_parents(cacheDir, 0o700);
    GLib.file_set_contents(`${cacheDir}/weather.json`, JSON.stringify(weatherState));
    const weatherOptions = {city:'Stockholm',countryCode:'SE',units:'celsius',showLocation:false,showConditions:false,showDetails:false,showForecast:false,showUpdated:false,showAttribution:false};
    settings.set_strv('desktop-enabled-widgets',['weather']);
    settings.set_string('desktop-widget-options',JSON.stringify({weather:weatherOptions}));
    const views = [{fixed,window,monitor:{id:'test',primary:true,width:1000,height:700}}];
    await host.mount(views); await wait(150);
    const compactHeight = host.instances[0].card.get_allocated_height();
    const compactRect = JSON.stringify(host.instances[0].rect);
    assert(compactHeight < 120, `Compact weather fits its visible content: ${compactHeight}`);
    await host.mount(views,true); await wait(100);
    assert(host.instances[0].card.get_allocated_height() === compactHeight && JSON.stringify(host.instances[0].rect) === compactRect, 'Weather keeps compact bounds in Edit Desktop');
    settings.set_string('desktop-widget-options',JSON.stringify({weather:{...weatherOptions,showForecast:true}}));
    await host.mount(views,true); await wait(100);
    assert(host.instances[0].card.get_allocated_height() > compactHeight, 'Forecast increases automatic weather height');
    settings.set_string('desktop-widget-options',JSON.stringify({weather:{...weatherOptions,autoHeight:false,height:220}}));
    await host.mount(views); await wait(100);
    assert(host.instances[0].card.get_allocated_height() >= 220, 'Explicit fixed weather height is retained');
    print('LUNA_DESKTOP_NEW_WIDGETS_PASS');
})().catch(e=>{failure=e;console.error(e);}).finally(()=>{host?.clear();for(const obj of exported)obj.unexport();for(const dispose of disposals)dispose();window.destroy();loop.quit();});
loop.run(); if(failure)throw failure;
