#!/usr/bin/env python3
"""Generate desktop key/value types from the standalone desktop schema."""
import json
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent.parent
schema = ET.parse(ROOT / 'schemas/org.gnome.shell.extensions.luna-desktop.gschema.xml').getroot().find('schema')
types = {'b': 'boolean', 'i': 'number', 's': 'string', 'as': 'string[]'}
lines = ['// Generated by scripts/generate-settings.py. Edit the XML schema instead.',
         'export interface SettingsValues {']
definitions = {}
for key in schema.findall('key'):
    name, kind = key.attrib['name'], key.attrib['type']
    if not name.startswith('desktop-'):
        raise ValueError('Only desktop settings belong to Luna - Desktop')
    choices = [choice.attrib['value'] for choice in key.findall('choices/choice')]
    value_type = ' | '.join(json.dumps(value) for value in choices) if choices else types[kind]
    lines.append(f'    {json.dumps(name)}: {value_type};')
    definition = {'type': kind}
    if choices:
        definition['choices'] = choices
    bounds = key.find('range')
    if bounds is not None:
        definition['range'] = [int(bounds.attrib['min']), int(bounds.attrib['max'])]
    definitions[name] = definition
lines += ['}', '', 'export const settingDefinitions = ' + json.dumps(definitions, indent=4) + ' as const;',
          'export type SettingKey = keyof SettingsValues;',
          'export type KeysOfType<T> = {[K in SettingKey]: SettingsValues[K] extends T ? K : never}[SettingKey];',
          'export const desktopKeys = Object.keys(settingDefinitions) as SettingKey[];', '']
(ROOT / 'src/settings/keys.ts').write_text('\n'.join(lines))
