// Generated by scripts/generate-settings.py. Edit the XML schema instead.
export interface SettingsValues {
    "desktop-icons-enabled": boolean;
    "desktop-show-home": boolean;
    "desktop-show-trash": boolean;
    "desktop-show-hidden": boolean;
    "desktop-single-click": boolean;
    "desktop-label-shadow": boolean;
    "desktop-label-color-override": boolean;
    "desktop-icon-size": number;
    "desktop-label-size": number;
    "desktop-corner-radius": number;
    "desktop-label-color": string;
    "desktop-monitor-mode": string;
    "desktop-icon-positions": string;
    "desktop-label-rows": number;
    "desktop-grid-spacing": number;
    "desktop-button-width": number;
    "desktop-arrange-corner": "top-left" | "top-right" | "bottom-left" | "bottom-right";
    "desktop-button-padding": number;
    "desktop-snap-to-grid": boolean;
    "desktop-highlight-grid": boolean;
    "desktop-show-external-drives": boolean;
    "desktop-show-network-drives": boolean;
    "desktop-drives-opposite": boolean;
    "desktop-widgets-enabled": boolean;
    "desktop-widget-snap-enabled": boolean;
    "desktop-widget-edge-spacing": number;
    "desktop-widget-snap-distance": number;
    "desktop-enabled-widgets": string[];
    "desktop-widget-positions": string;
    "desktop-sort-order": "name" | "type" | "modified" | "size";
    "desktop-widget-options": string;
    "desktop-accent-color": string;
    "desktop-app-menu-enabled": boolean;
    "desktop-switcher-opacity": number;
    "desktop-switcher-blur-radius": number;
    "desktop-switcher-corner-radius": number;
    "desktop-switcher-padding": number;
    "desktop-switcher-card-spacing": number;
    "desktop-switcher-transparency": boolean;
    "desktop-switcher-color-override": boolean;
    "desktop-switcher-color": string;
    "desktop-switcher-width-percent": number;
    "desktop-switcher-primary-monitor": boolean;
    "desktop-snap-switcher-enabled": boolean;
    "desktop-snap-enabled": boolean;
    "desktop-snap-bar-enabled": boolean;
    "desktop-snap-assist-enabled": boolean;
    "desktop-snap-layout-shortcut": string[];
    "desktop-snap-left": string[];
    "desktop-snap-right": string[];
    "desktop-snap-up": string[];
    "desktop-snap-down": string[];
    "desktop-snap-gap": number;
    "desktop-snap-square-corners": boolean;
}

export const settingDefinitions = {
    "desktop-icons-enabled": {
        "type": "b"
    },
    "desktop-show-home": {
        "type": "b"
    },
    "desktop-show-trash": {
        "type": "b"
    },
    "desktop-show-hidden": {
        "type": "b"
    },
    "desktop-single-click": {
        "type": "b"
    },
    "desktop-label-shadow": {
        "type": "b"
    },
    "desktop-label-color-override": {
        "type": "b"
    },
    "desktop-icon-size": {
        "type": "i",
        "range": [
            24,
            96
        ]
    },
    "desktop-label-size": {
        "type": "i",
        "range": [
            9,
            24
        ]
    },
    "desktop-corner-radius": {
        "type": "i",
        "range": [
            0,
            24
        ]
    },
    "desktop-label-color": {
        "type": "s"
    },
    "desktop-monitor-mode": {
        "type": "s"
    },
    "desktop-icon-positions": {
        "type": "s"
    },
    "desktop-label-rows": {
        "type": "i",
        "range": [
            1,
            5
        ]
    },
    "desktop-grid-spacing": {
        "type": "i",
        "range": [
            0,
            32
        ]
    },
    "desktop-button-width": {
        "type": "i",
        "range": [
            80,
            200
        ]
    },
    "desktop-arrange-corner": {
        "type": "s",
        "choices": [
            "top-left",
            "top-right",
            "bottom-left",
            "bottom-right"
        ]
    },
    "desktop-button-padding": {
        "type": "i",
        "range": [
            0,
            24
        ]
    },
    "desktop-snap-to-grid": {
        "type": "b"
    },
    "desktop-highlight-grid": {
        "type": "b"
    },
    "desktop-show-external-drives": {
        "type": "b"
    },
    "desktop-show-network-drives": {
        "type": "b"
    },
    "desktop-drives-opposite": {
        "type": "b"
    },
    "desktop-widgets-enabled": {
        "type": "b"
    },
    "desktop-widget-snap-enabled": {
        "type": "b"
    },
    "desktop-widget-edge-spacing": {
        "type": "i",
        "range": [
            0,
            128
        ]
    },
    "desktop-widget-snap-distance": {
        "type": "i",
        "range": [
            2,
            32
        ]
    },
    "desktop-enabled-widgets": {
        "type": "as"
    },
    "desktop-widget-positions": {
        "type": "s"
    },
    "desktop-sort-order": {
        "type": "s",
        "choices": [
            "name",
            "type",
            "modified",
            "size"
        ]
    },
    "desktop-widget-options": {
        "type": "s"
    },
    "desktop-accent-color": {
        "type": "s"
    },
    "desktop-app-menu-enabled": {
        "type": "b"
    },
    "desktop-switcher-opacity": {
        "type": "i",
        "range": [
            0,
            100
        ]
    },
    "desktop-switcher-blur-radius": {
        "type": "i",
        "range": [
            0,
            100
        ]
    },
    "desktop-switcher-corner-radius": {
        "type": "i",
        "range": [
            0,
            32
        ]
    },
    "desktop-switcher-padding": {
        "type": "i",
        "range": [
            0,
            24
        ]
    },
    "desktop-switcher-card-spacing": {
        "type": "i",
        "range": [
            0,
            24
        ]
    },
    "desktop-switcher-transparency": {
        "type": "b"
    },
    "desktop-switcher-color-override": {
        "type": "b"
    },
    "desktop-switcher-color": {
        "type": "s"
    },
    "desktop-switcher-width-percent": {
        "type": "i",
        "range": [
            40,
            95
        ]
    },
    "desktop-switcher-primary-monitor": {
        "type": "b"
    },
    "desktop-snap-switcher-enabled": {
        "type": "b"
    },
    "desktop-snap-enabled": {
        "type": "b"
    },
    "desktop-snap-bar-enabled": {
        "type": "b"
    },
    "desktop-snap-assist-enabled": {
        "type": "b"
    },
    "desktop-snap-layout-shortcut": {
        "type": "as"
    },
    "desktop-snap-left": {
        "type": "as"
    },
    "desktop-snap-right": {
        "type": "as"
    },
    "desktop-snap-up": {
        "type": "as"
    },
    "desktop-snap-down": {
        "type": "as"
    },
    "desktop-snap-gap": {
        "type": "i",
        "range": [
            0,
            48
        ]
    },
    "desktop-snap-square-corners": {
        "type": "b"
    }
} as const;
export type SettingKey = keyof SettingsValues;
export type KeysOfType<T> = {[K in SettingKey]: SettingsValues[K] extends T ? K : never}[SettingKey];
export const desktopKeys = Object.keys(settingDefinitions) as SettingKey[];
